export const reducerCases = {
    FETCH_ADDRESS_SUCCESS:"FETCH_ADDRESS_SUCCESS",
    ADD_ADDRESS_SUCCESS: "ADD_ADDRESS_SUCCESS",
    DELETE_ADDRESS_SUCCESS:"DELETE_ADDRESS_SUCCESS",
    UPDATE_ADDRESS_SUCCESS:"UPDATE_ADDRESS_SUCCESS",
    ADDRESS_ERROR:"ADDRESS_ERROR",
  };
  