export const reducerCases = {
  INITIALIZE_CART:"INITIALIZE_CART",
  ADD_TO_CART: "ADD_TO_CART_SUCCESS",
  REMOVE_FROM_CART: "REMOVE_FROM_CART_SUCCESS",
  INCREMENT_QUANTITY: "INCREMENT_QUANTITY_SUCCESS",
  DECREMENT_QUANTITY: "DECREMENT_QUANTITY_SUCCESS",
  CART_ERROR: "CART_ERROR",
  CLEAR_CART:"CLEAR_CART",
};
