export const reducerCases = {
  FETCH_CATEGORIES_SUCCESS:"FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILURE:"FETCH_CATEGORIES_FAILURE",
  ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
  ADD_CATEGORY_FAILURE: "ADD_CATEGORY_FAILURE",
  DELETE_CATEGORY_SUCCESS:"DELETE_CATEGORY_SUCCESS",
  DELETE_CATEGORY_FAILURE:"DELETE_CATEGORY_FAILURE",
  UPDATE_CATEGORY_SUCCESS:"UPDATE_CATEGORY_SUCCESS",
  UPDATE_CATEGORY_FAILURE:"UPDATE_CATEGORY_FAILURE",
};
