export const reducerCases = {
    FETCH_PRODUCTS_SUCCESS:"FETCH_PRODUCTS_SUCCESS",
    FETCH_PRODUCTS_FAILURE:"FETCH_PRODUCTS_FAILURE",
    ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
    ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",
    DELETE_PRODUCT_SUCCESS:"DELETE_PRODUCT_SUCCESS",
    DELETE_PRODUCT_FAILURE:"DELETE_PRODUCT_FAILURE",
    UPDATE_PRODUCT_SUCCESS:"UPDATE_PRODUCT_SUCCESS",
    UPDATE_PRODUCT_FAILURE:"UPDATE_PRODUCT_FAILURE",
  };
  